### ISSUE TITLE
icd_explain("0381")  gives wrong description

### ISSUE THREAD

**Issue by opsdoc0** [jackwasey/icd#113]
It gives "Arthropod-borne disease, unspecified", which is ICD-9 code "0889" .
It should give 038.1 Staphylococcal septicemia

**Comment by jackwasey** [comment]
Thanks for the report. A couple of these have popped up due to the automated parsing. I'm going to see if I can tweak the parsing easily: if not, I'm going to add this to a currently very small list of manual exceptions where the parsing doesn't work. It would be helpful if you could take a look at neighboring codes, and determine the entire range affected, or whether it is indeed just one. Thanks again.
