### ISSUE TITLE
add AHRQ CCS rollups

### ISSUE THREAD

**Issue by ababayan13** [jackwasey/icd#127]
It would be nice to have AHRQ CCS rollups in the software. Many researcher use it.

**Comment by jackwasey** [comment]
Agreed, it would be a good addition. Is there anyone interested in working on this? I'd be happy to co-ordinate and merge code.

**Comment by vitallish** [comment]
I'd be interested in getting started on this. I see there are some AHRQ CCS files in date_raw for icd9. My understanding of the process is as follows:

1. Update the ICD10/9 files from https://www.hcup-us.ahrq.gov/toolssoftware/ccs10/ccs10.jsp and https://www.hcup-us.ahrq.gov/toolssoftware/ccs/ccs.jsp
2. Write some parsing functions to the R folder eg `parse-ahrq-ccs` to create mapping files to be saved in the data directory. These map files are named lists (again using icd10_map_ahrq as a template.
3. Create 3 functions - icd9_comorbid_ahrq_ccs, icd10_comorbid_ahrq_ccs and icd_comorbid_ahrq_ccs similar to how the comorbid_ahrq functions. These will use the map file created in 2.

As i'm looking through some of your comments in the `comorbid.R` file I see some comments about using a lookup table instead of the lists used. This definitely makes sense to me from a performance perspective. Is there any way that I could start down this path for the AHRQ CCS? I imagine this would require creating a new icd9/10_comorbid function that would use a dataframe for map rather than the lists.

**Comment by jackwasey** [comment]
This sounds like a great plan, thanks!

I should probably put some things in the contribution guidelines, but please:
 - avoid dplyr etc (I like them, but it adds a huge dependency burden)
 - don't start with performance as a goal: we can work on that later
 - plenty of tests! (so we can refactor for performance later)
 - plenty of documentation and examples

Some people are using this on many Gb of data, so I do really value performance once the basics are working. We can optimize the R and consider Rcpp/C++ if needed.

Also note that the output is matrix by default: it is numerically consistent given the data all has same type, and much quicker to compute. It is also fast to convert to data.frame (but the converse is not true). It is not "tidy", i.e I have to use row names for identifiers, but this made a huge speed improvement.

One small thing, if you are creating temporary intermediate files as it seems you describe, you will need to clean them up, otherwise CRAN goes berserk.
