### ISSUE TITLE
unable to install from github

### ISSUE THREAD

**Issue by anobel** [jackwasey/icd#135]
I'm able to get the package installed from CRAN, but running into issues installing locally or from GitHub using `devtools`. I initially had a lot of issues with OpenMP, followed the instructions from [Coatless Professor](https://thecoatlessprofessor.com/programming/openmp-in-r-on-os-x/#after-3-4-0) which I think helped with that issue, but now not sure what the problem is. likely a local issue, no?

```
installing to /Library/Frameworks/R.framework/Versions/3.4/Resources/library/icd/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Warning: S3 methods ‘icd_decimal_to_parts.icd10’, ‘icd_short_to_parts.icd10’ were declared in NAMESPACE but not found
Error: package or namespace load failed for ‘icd’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/icd/libs/icd.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/icd/libs/icd.so, 6): Symbol not found: __icd_RcppExport_registerCCallable
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/icd/libs/icd.so
  Expected in: flat namespace
 in /Library/Frameworks/R.framework/Versions/3.4/Resources/library/icd/libs/icd.so
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/icd’
Installation failed: Command failed (1)

```

**Comment by jackwasey** [comment]
Hmm, there was some C/C++ registration stuff which is now required. I
wonder whether you might have success by cleaning the build tree
(Rstudio Clean and Rebuild). I haven't touched the OpenMP stuff for a
while, and this hasn't been a problem with me across three platforms and
in docker containers. Also, make sure you document() before buildling. I
took out some auto-generated Rcpp stuff from the git tree, because Rcpp
made it different each time and it was cluttering the git history badly.
LMK if neither of these things works.

Cheers,
Jack

**Comment by anobel** [comment]
I think I'm not understanding devtools basics. Ive previously just used `install_github("user/repo@branch")` and `install_local` to install `icd`

works fine from `CRAN`

Even after a clean rebuild of Rstudio, I still get the above error. However when I run `document()`, it loads `icd`

```
Updating icd documentation
Loading icd
Welcome to the "icd" package for finding comorbidities and interpretation of ICD-9 and ICD-10 codes. Suggestions and contributions are welcome at https://github.com/jackwasey/icd .

See the vignettes and help for examples.

Please cite this package if you find it useful in your published work.
citation(package = "icd")

Will skip slow tests
```

But I'm unclear on which version of ICD I'm installing? 

sorry, I must be doing something daft

**Comment by jackwasey** [comment]
Hey, sorry I just saw your reply.

I will put the Rcpp generated code back in github so install_github works. It's really annoying because Rcpp doesn't seem to be deterministic, so every time I build the package, the order of functions in the Rcpp generated code changes, resulting in the git history being bloated. The workaround until I do this is to git pull the repo, start R in the package root, and write `devtools::document()`.

**Comment by jackwasey** [comment]
`Rcpp::compileAttributes()` is actually what generates those files.
