### ISSUE TITLE
Issues with ICD package for 3-digit codes

### ISSUE THREAD

**Issue by rcih** [jackwasey/icd#155]
Hi @jackwasey 
I am trying to use the ICD package to convert the ICD9 codes in my data into disease comorbidity groups using the CCS classification. 
This is a sample of my dataset:

> head((test),10)
   visit_id  icd9
1         1  4019
2         2   250
3         3  2724
4         4   414
5         5  4939
6         6 53081
7         7 41401
8         8   272
9         9 78605
10       10  7865

When I tried to use the comorbid_ccs() function and the comorbid_charlson() function, I only see FALSE values in the output for all of the codes, even though I know that, for example, 250 is the code for Diabetes Mellitus. I am not pasting the output because it is a lot.
I think it is not recognizing my codes because some of them are 3-digits and 4-digits.
Example-However, when I use the explain_code() function to test whether it can explain different variations of the same code, I end up with the correct explanation each time.
> explain_code("250")
[1] "Diabetes mellitus"
> explain_code("25000")
[1] "Diabetes mellitus without mention of complication, type II or unspecified type, not stated as uncontrolled"
> explain_code("250.00")
[1] "Diabetes mellitus without mention of complication, type II or unspecified type, not stated as uncontrolled"
I have also checked the structure of my dataset to make sure that the ICD9 codes are factors 

So, I am not sure where I am going wrong and how to go about using this package.
Your help is greatly appreciated!
Thank you.

**Comment by jackwasey** [comment]
Thanks for writing that out. You're right: the problem is the 3-digit code you have. The source file from AHRQ does not contain the code "250" which is not a 'billable' code, but a hierarchy member. This is a little annoying, as I've tried really hard to make a transparent path from raw data from the source through to the R results which 'icd' gives, and I'm reluctant to change the intention of the authors of the source data. What is your opinion?

```
library(icd)
library(magrittr)
icd::icd9_map_multi_ccs %>%  unlist %>%  unname %>% grep(pattern = "^250", value = TRUE) %>%  condense(defined = TRUE)
```

Also, if you have the source tree from a git clone, you can rebuild the data file:
```
icd9_fetch_ahrq_ccs(single = TRUE, offline = FALSE)
```
Then in a bash terminal, you can confirm there is no '250':
```
grep "^\'250.*\'" X.dxref.2015.csv
```

**Comment by rcih** [comment]
Oh, I see. That makes complete sense that you don't want to tamper with the intent of the source data.

Regarding rebuilding of the data file, could you please elaborate on that, I'm not sure I understand. 

And thank you again for your prompt responses, it has been extremely helpful.

**Comment by jackwasey** [comment]
No need to rebuild the data files internal to icd. I was merely demonstration that replication of the data generation all the way from the internet resource through to the icd R package is possible. If you are skilled, you can force '250' to be inserted during this process, but I wouldn't recommend it. Better to work with your data if possible. Why is 250 appearing, since it is not a diagnostic code?

If other people are encountering this, we could consider broadening the accepted codes so 250 (and similar situations) would be included, but this, as I explained, would not match the intention of AHRQ, so would require some discussion.
